# Generated by Django 3.0.6 on 2021-01-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20210120_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(upload_to='test'),
        ),
    ]
