# Generated by Django 3.0.6 on 2021-01-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20210120_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
